### ISSUE TITLE
How to build on Ubuntu 25.10

### ISSUE THREAD

**Issue by AndreiCherniaev** [wimstockman/receipt_demo#3]
My steps.
1. install [finalcut](https://github.com/gansm/finalcut/issues/154#issuecomment-3776093565)
2. build receipt_demo example
```
git clone https://github.com/wimstockman/receipt_demo
cd receipt_demo
make -j$(( $(nproc) + 1))
```
But error
```
g++ -g -Wall -lfinal   -o receipt_demo receipt_demo.cpp
/usr/bin/ld: /tmp/ccMd45zc.o: warning: relocation against `_ZN8finalcut7FWidget12focus_widgetE' in read-only section `.text._ZN8finalcut7FWidget14getFocusWidgetEv[_ZN8finalcut7FWidget14getFocusWidgetEv]'
/usr/bin/ld: /tmp/ccMd45zc.o: in function `main':
/home/q/finalcut/receipt_demo/receipt_demo.cpp:322:(.text+0x5d): undefined reference to `finalcut::FApplication::FApplication(int const&, char**)'
/usr/bin/ld: /home/q/finalcut/receipt_demo/receipt_demo.cpp:323:(.text+0x6c): undefined reference to `finalcut::FApplication::initTerminal()'
/usr/bin/ld: /home/q/finalcut/receipt_demo/receipt_demo.cpp:327:(.text+0x9e): undefined reference to `finalcut::FString::FString(char const*)'
/usr/bin/ld: /home/q/finalcut/receipt_demo/receipt_demo.cpp:327:(.text+0xc6): undefined reference to `finalcut::FString::~FString()'
/usr/bin/ld: /home/q/finalcut/receipt_demo/receipt_demo.cpp:328:(.text+0x11a): undefined reference to `finalcut::FWindow::setGeometry(finalcut::FPoint const&, finalcut::FSize const&, bool)'
/usr/bin/ld: /home/q/finalcut/receipt_demo/receipt_demo.cpp:329:(.text+0x129): undefined reference to `finalcut::FWidget::redraw()'
/usr/bin/ld: /home/q/finalcut/receipt_demo/receipt_demo.cpp:330:(.text+0x138): undefined reference to `finalcut::FWidget::setMainWidget(finalcut::FWidget*)'
...
```
How to fix?

**Comment by wimstockman** [comment]
Hi , 
yes indeed it seems i have to update my program. It works with an older version of finalcut. I'll look into it next week. thx for pointing out.

**Comment by wimstockman** [comment]
Ok , I updated the code.
Let me know if you have any other hickups.
Kind Regards,
Wim Stockman
